version: '3.0'

services:
  # Container name 就是 redis/website 等
  # Website Redis
  redis:
    image: redis
    container_name: website-redis
    ports:
      - "${REDIS_PORT}:6379"

  # Website Account Server
  website-account:
    build: ./website-account
    image: website/website-account
    container_name: website-account
    ports:
      - "${WEBSITE_ACCOUNT_PORT}:3001"
    volumes:
      - "${WEBSITE_SRC}:/website/src"
      - "${WEBSITE_LOG_DIR}:/website/log"
    environment:
      NODE_ENV: development
    depends_on:
      - redis

  # Website Admin Server
  website-admin:
    build: ./website-admin
    image: website/website-admin
    container_name: website-admin
    ports:
      # Express use port:3000
      - "${WEBSITE_ADMIN_PORT}:3000"
    volumes:
      - "${WEBSITE_SRC}:/website/src"
      - "${WEBSITE_LOG_DIR}:/website/log"
    environment:
      NODE_ENV: development
    depends_on:
      - redis

  # Website Nginx
  nginx:
    build: ./nginx
    image: website/nginx
    container_name: website-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "${WEBSITE_SRC}:/website/src"
    depends_on:
      - website-account
      - website-admin
