version: '3.0'

services:
  # Container name 就是 redis/blog 等
  # Blog Redis
  redis:
    image: redis
    container_name: blog-redis
    ports:
      - "${REDIS_PORT}:6379"

  # Blog Server
  blog:
    build: ./blog
    image: blog/blog
    container_name: blog
    ports:
      # Node use port:3000
      - "${BLOG_PORT}:3000"
    volumes:
      - "${BLOG_SRC}:/blog/src"
      - "${BLOG_LOG_DIR}:/blog/log"
    environment:
      NODE_ENV: development
    depends_on:
      - redis

  # Blog Nginx
  nginx:
    build: ./nginx
    image: blog/nginx
    container_name: blog-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "${BLOG_SRC}:/blog/src"
    depends_on:
      - blog
