version: '3'
services:
  # Website Redis
  redis:
    image: redis
    container_name: website-redis
    ports:
      - "${REDIS_PORT}:6379"
  # Website Server
  website:
    build: ./website
    container_name: website
    ports:
      - "${WEBSITE_PORT}:80"
    volumes:
      - "${WEBSITE_SRC}:/website/lib/website"
      - "${WEBSITE_LOG_DIR}:/website/log"
