version: '3.0'

services:
  # Website Redis
  redis:
    image: redis
    container_name: website-redis
    ports:
      - "${REDIS_PORT}:6379"

  # Website Server
  website:
    build: ./website
    image: website/website
    container_name: website
    ports:
      # Node use port:3000
      - "${WEBSITE_PORT}:3000"
    volumes:
      - "/Users/wanglei/Documents/private-projects/website:/website/src"
      - "${WEBSITE_LOG_DIR}:/website/log"
    environment:
      NODE_ENV: development
    depends_on:
      - redis

  nginx:
    build: ./nginx
    image: website/nginx
    container_name: website-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "${WEBSITE_SRC}:/website/src"
    depends_on:
      - website
